### ISSUE TITLE
Is Svelte 3 supported?

### ISSUE THREAD

**Issue by ptrxyz** [metafy-gg/vite-plugin-svelte-svg#1]
Hello!

Does this plugin work for Svelte 3 (used with Vite)? Or is it SvelteKit only?

Cheers,
Peter

**Comment by janbaer** [comment]
It worked for me with Svelte 3. But I have issues after upgrading from vite 2.6.2 to 2.7.2

**Comment by cibernox** [comment]
@janbaer What issues are you facing? I'm just trying out this and I get the `Logo is not a constructor` (assuming I do `import Logo from 'assets/icons/logo.svg?component`)

**Comment by janbaer** [comment]
@cibernox I get the same error

**Comment by cibernox** [comment]
@janbaer I also tried rollup-plugin-svelte-svg and failed, but in this comment I found a custom plugin that worked great for me: https://github.com/codefeathers/rollup-plugin-svelte-svg/issues/31#issuecomment-982351402
