### ISSUE TITLE
Add TypeScript example

### ISSUE THREAD

**Issue by ai** [metafy-gg/vite-plugin-svelte-svg#4]
Of course, `*.svg` files doesn’t have types.

We can improve user’s onboarding by adding some solution for TypeScript, since it is very widely used.

**Comment by vincerubinetti** [comment]
How do I type the imports to get rid of this error:

```
Cannot find module '@/icons/play.svg?component' or its corresponding type declarations.
```

Normally I would do:

```
declare module "svg";
```

But that gets tripped up by the odd `?component`. How do I account for that in my module declaration?

Related: https://github.com/microsoft/TypeScript/issues/38638

**Comment by vincerubinetti** [comment]
I think this is a solution:

```ts
declare module "*svg?component" {
  import { ComponentType, SvelteComponentTyped } from "svelte";
  const icon: ComponentType<SvelteComponentTyped>;
  export default icon;
}
```

Though this doesn't work for importing the component in Astro too, which I'm using.
