### ISSUE TITLE
No sourcemap warning

### ISSUE THREAD

**Issue by cibernox** [metafy-gg/vite-plugin-svelte-svg#7]
I'm getting this error when building my app for production with this plugin:

```
Sourcemap is likely to be incorrect: a plugin (svelte-svg) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```

Is this something you're aware of?

**Comment by trmcnvn** [comment]
Thanks, we're not using this in our internal code currently so these kind of issues are missed.

It looks like we're not outputting the map generated by the Svelte compiler.

**Comment by trmcnvn** [comment]
Fixed in https://github.com/metafy-gg/vite-plugin-svelte-svg/commit/7f60563a4375ecbe6c9b111cd8bdac4cdd5d9b1c
